use phf::phf_map;
use xu_syntax::TokenKind;

pub(crate) static KEYWORDS_EN: phf::Map<&'static str, TokenKind> = phf_map! {
    "true" => TokenKind::True,
    "false" => TokenKind::False,
    "if" => TokenKind::KwIf,
    "else" => TokenKind::KwElse,
    "while" => TokenKind::KwWhile,
    "for" => TokenKind::KwFor,
    "in" => TokenKind::KwIn,
    "return" => TokenKind::KwReturn,
    "break" => TokenKind::KwBreak,
    "continue" => TokenKind::KwContinue,
    "let" => TokenKind::KwLet,
    "var" => TokenKind::KwVar,
    "is" => TokenKind::KwIs,
    "with" => TokenKind::KwWith,
    "has" => TokenKind::KwHas,
    "does" => TokenKind::KwDoes,
    "pub" => TokenKind::KwPub,
    "static" => TokenKind::KwStatic,
    "self" => TokenKind::KwSelf,
    "use" => TokenKind::KwUse,
    "as" => TokenKind::KwAs,
    "func" => TokenKind::KwFunc,
    "match" => TokenKind::KwMatch,
    "when" => TokenKind::KwWhen,
    "can" => TokenKind::KwCan,
    "async" => TokenKind::KwAsync,
    "await" => TokenKind::KwAwait,
};
